version: '3.7'

# https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef
# connection string: mongodb://root:rootpassword@localhost:27017/?authSource=admin&readPreference=primary&ssl=false

services:
  mongodb:
    container_name: mongo_dev
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mendeleev
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - dev

volumes:
  mongodb_data_container:

networks:
  dev:
    driver: bridge
